var fs = require('fs'),
  emojiLib = require('emojilib'),
  inflection = require('inflection'),
  mkdirp = require('mkdirp')

var { compress } = require('../src/utils/data')

var categories = [
  ['Smileys & People', 'people'],
  ['Animals & Nature', 'nature'],
  ['Food & Drink', 'foods'],
  ['Activities', 'activity'],
  ['Travel & Places', 'places'],
  ['Objects', 'objects'],
  ['Symbols', 'symbols'],
  ['Flags', 'flags'],
]

var smilesAndPeople = [
  "grinning",
  "grin",
  "joy",
  "smiley",
  "smile",
  "sweat_smile",
  "wink",
  "blush",
  "yum",
  "sunglasses",
  "heart_eyes",
  "kissing_heart",
  "kissing",
  "kissing_smiling_eyes",
  "kissing_closed_eyes",
  "relaxed",
  "neutral_face",
  "expressionless",
  "no_mouth",
  "smirk",
  "persevere",
  "disappointed_relieved",
  "open_mouth",
  "hushed",
  "sleepy",
  "tired_face",
  "sleeping",
  "relieved",
  "stuck_out_tongue",
  "stuck_out_tongue_winking_eye",
  "stuck_out_tongue_closed_eyes",
  "unamused",
  "sweat",
  "pensive",
  "confused",
  "astonished",
  "confounded",
  "disappointed",
  "worried",
  "triumph",
  "cry",
  "sob",
  "frowning",
  "anguished",
  "fearful",
  "weary",
  "grimacing",
  "cold_sweat",
  "scream",
  "flushed",
  "dizzy_face",
  "rage",
  "angry",
  "mask",
  "innocent",
  "smiling_imp",
  "imp",
  "japanese_ogre",
  "japanese_goblin",
  "skull",
  "ghost",
  "alien",
  "space_invader",
  "hankey",
  "smiley_cat",
  "smile_cat",
  "joy_cat",
  "heart_eyes_cat",
  "smirk_cat",
  "kissing_cat",
  "scream_cat",
  "crying_cat_face",
  "pouting_cat",
  "see_no_evil",
  "hear_no_evil",
  "speak_no_evil",
  "baby",
  "boy",
  "girl",
  "man",
  "woman",
  "older_man",
  "older_woman",
  "cop",
  "guardsman",
  "construction_worker",
  "princess",
  "man_with_turban",
  "man_with_gua_pi_mao",
  "person_with_blond_hair",
  "bride_with_veil",
  "angel",
  "santa",
  "person_frowning",
  "person_with_pouting_face",
  "no_good",
  "ok_woman",
  "information_desk_person",
  "raising_hand",
  "bow",
  "massage",
  "haircut",
  "walking",
  "runner",
  "dancer",
  "dancers",
  "bath",
  "bust_in_silhouette",
  "busts_in_silhouette",
  "horse_racing",
  "snowboarder",
  "surfer",
  "rowboat",
  "swimmer",
  "bicyclist",
  "mountain_bicyclist",
  "couple",
  "two_men_holding_hands",
  "two_women_holding_hands",
  "couplekiss",
  "couple_with_heart",
  "muscle",
  "point_left",
  "point_right",
  "point_up",
  "point_up_2",
  "point_down",
  "v",
  "hand",
  "ok_hand",
  "+1",
  "-1",
  "fist",
  "facepunch",
  "wave",
  "clap",
  "open_hands",
  "raised_hands",
  "pray",
  "nail_care",
  "ear",
  "nose",
  "footprints",
  "eyes",
  "tongue",
  "lips",
  "kiss",
  "cupid",
  "heart",
  "heartbeat",
  "broken_heart",
  "two_hearts",
  "sparkling_heart",
  "heartpulse",
  "blue_heart",
  "green_heart",
  "yellow_heart",
  "purple_heart",
  "gift_heart",
  "revolving_hearts",
  "heart_decoration",
  "love_letter",
  "zzz",
  "anger",
  "bomb",
  "boom",
  "sweat_drops",
  "dash",
  "dizzy",
  "speech_balloon",
  "thought_balloon",
  "eyeglasses",
  "necktie",
  "shirt",
  "jeans",
  "dress",
  "kimono",
  "bikini",
  "womans_clothes",
  "purse",
  "handbag",
  "pouch",
  "school_satchel",
  "mans_shoe",
  "athletic_shoe",
  "high_heel",
  "sandal",
  "boot",
  "crown",
  "womans_hat",
  "tophat",
  "mortar_board",
  "lipstick",
  "ring",
  "gem"
];
var animalsAndNature = [
  "monkey_face",
  "monkey",
  "dog",
  "dog2",
  "poodle",
  "wolf",
  "cat",
  "cat2",
  "tiger",
  "tiger2",
  "leopard",
  "horse",
  "racehorse",
  "cow",
  "ox",
  "water_buffalo",
  "cow2",
  "pig",
  "pig2",
  "boar",
  "pig_nose",
  "ram",
  "sheep",
  "goat",
  "dromedary_camel",
  "camel",
  "elephant",
  "mouse",
  "mouse2",
  "rat",
  "hamster",
  "rabbit",
  "rabbit2",
  "bear",
  "koala",
  "panda_face",
  "feet",
  "chicken",
  "rooster",
  "hatching_chick",
  "baby_chick",
  "hatched_chick",
  "bird",
  "penguin",
  "frog",
  "crocodile",
  "turtle",
  "snake",
  "dragon_face",
  "dragon",
  "whale",
  "whale2",
  "dolphin",
  "fish",
  "tropical_fish",
  "blowfish",
  "octopus",
  "shell",
  "snail",
  "bug",
  "ant",
  "bee",
  "beetle",
  "bouquet",
  "cherry_blossom",
  "white_flower",
  "rose",
  "hibiscus",
  "sunflower",
  "blossom",
  "tulip",
  "seedling",
  "evergreen_tree",
  "deciduous_tree",
  "palm_tree",
  "cactus",
  "ear_of_rice",
  "herb",
  "four_leaf_clover",
  "maple_leaf",
  "fallen_leaf",
  "leaves"
];

var activity = [
  "jack_o_lantern",
  "christmas_tree",
  "fireworks",
  "sparkler",
  "sparkles",
  "balloon",
  "tada",
  "confetti_ball",
  "tanabata_tree",
  "bamboo",
  "dolls",
  "flags",
  "wind_chime",
  "rice_scene",
  "ribbon",
  "gift",
  "ticket",
  "trophy",
  "soccer",
  "baseball",
  "basketball",
  "football",
  "rugby_football",
  "tennis",
  "8ball",
  "bowling",
  "dart",
  "golf",
  "fishing_pole_and_fish",
  "running_shirt_with_sash",
  "ski",
  "video_game",
  "game_die",
  "spades",
  "hearts",
  "diamonds",
  "clubs",
  "black_joker",
  "mahjong",
  "flower_playing_cards"
];

var travelAndPlaces = [
  "earth_africa",
  "earth_americas",
  "earth_asia",
  "globe_with_meridians",
  "japan",
  "volcano",
  "mount_fuji",
  "house",
  "house_with_garden",
  "office",
  "post_office",
  "european_post_office",
  "hospital",
  "bank",
  "hotel",
  "love_hotel",
  "convenience_store",
  "school",
  "department_store",
  "factory",
  "japanese_castle",
  "european_castle",
  "wedding",
  "tokyo_tower",
  "statue_of_liberty",
  "church",
  "fountain",
  "tent",
  "foggy",
  "night_with_stars",
  "sunrise_over_mountains",
  "sunrise",
  "city_sunset",
  "city_sunrise",
  "bridge_at_night",
  "hotsprings",
  "milky_way",
  "carousel_horse",
  "ferris_wheel",
  "roller_coaster",
  "barber",
  "circus_tent",
  "performing_arts",
  "art",
  "slot_machine",
  "steam_locomotive",
  "railway_car",
  "bullettrain_side",
  "bullettrain_front",
  "train2",
  "metro",
  "light_rail",
  "station",
  "tram",
  "monorail",
  "mountain_railway",
  "train",
  "bus",
  "oncoming_bus",
  "trolleybus",
  "minibus",
  "ambulance",
  "fire_engine",
  "police_car",
  "oncoming_police_car",
  "taxi",
  "oncoming_taxi",
  "car",
  "oncoming_automobile",
  "blue_car",
  "truck",
  "articulated_lorry",
  "tractor",
  "bike",
  "busstop",
  "fuelpump",
  "rotating_light",
  "traffic_light",
  "vertical_traffic_light",
  "construction",
  "anchor",
  "boat",
  "speedboat",
  "ship",
  "airplane",
  "seat",
  "helicopter",
  "suspension_railway",
  "mountain_cableway",
  "aerial_tramway",
  "satellite",
  "rocket",
  "door",
  "toilet",
  "shower",
  "bathtub",
  "hourglass",
  "hourglass_flowing_sand",
  "watch",
  "alarm_clock",
  "clock12",
  "clock1230",
  "clock1",
  "clock130",
  "clock2",
  "clock230",
  "clock3",
  "clock330",
  "clock4",
  "clock430",
  "clock5",
  "clock530",
  "clock6",
  "clock630",
  "clock7",
  "clock730",
  "clock8",
  "clock830",
  "clock9",
  "clock930",
  "clock10",
  "clock1030",
  "clock11",
  "clock1130",
  "new_moon",
  "waxing_crescent_moon",
  "first_quarter_moon",
  "moon",
  "full_moon",
  "waning_gibbous_moon",
  "last_quarter_moon",
  "waning_crescent_moon",
  "crescent_moon",
  "new_moon_with_face",
  "first_quarter_moon_with_face",
  "last_quarter_moon_with_face",
  "sunny",
  "full_moon_with_face",
  "sun_with_face",
  "star",
  "star2",
  "stars",
  "cloud",
  "partly_sunny",
  "cyclone",
  "rainbow",
  "closed_umbrella",
  "umbrella",
  "zap",
  "snowflake",
  "snowman",
  "fire",
  "droplet",
  "ocean"
];

var symbols = [
  "atm",
  "put_litter_in_its_place",
  "potable_water",
  "wheelchair",
  "mens",
  "womens",
  "restroom",
  "baby_symbol",
  "wc",
  "passport_control",
  "customs",
  "baggage_claim",
  "left_luggage",
  "warning",
  "children_crossing",
  "no_entry",
  "no_entry_sign",
  "no_bicycles",
  "no_smoking",
  "do_not_litter",
  "non-potable_water",
  "no_pedestrians",
  "no_mobile_phones",
  "underage",
  "arrow_up",
  "arrow_upper_right",
  "arrow_right",
  "arrow_lower_right",
  "arrow_down",
  "arrow_lower_left",
  "arrow_left",
  "arrow_upper_left",
  "arrow_up_down",
  "left_right_arrow",
  "leftwards_arrow_with_hook",
  "arrow_right_hook",
  "arrow_heading_up",
  "arrow_heading_down",
  "arrows_clockwise",
  "arrows_counterclockwise",
  "back",
  "end",
  "on",
  "soon",
  "top",
  "six_pointed_star",
  "aries",
  "taurus",
  "gemini",
  "cancer",
  "leo",
  "virgo",
  "libra",
  "scorpius",
  "sagittarius",
  "capricorn",
  "aquarius",
  "pisces",
  "ophiuchus",
  "twisted_rightwards_arrows",
  "repeat",
  "repeat_one",
  "arrow_forward",
  "fast_forward",
  "arrow_backward",
  "rewind",
  "arrow_up_small",
  "arrow_double_up",
  "arrow_down_small",
  "arrow_double_down",
  "cinema",
  "low_brightness",
  "high_brightness",
  "signal_strength",
  "vibration_mode",
  "mobile_phone_off",
  "recycle",
  "trident",
  "name_badge",
  "beginner",
  "o",
  "white_check_mark",
  "ballot_box_with_check",
  "heavy_check_mark",
  "heavy_multiplication_x",
  "x",
  "negative_squared_cross_mark",
  "heavy_plus_sign",
  "heavy_minus_sign",
  "heavy_division_sign",
  "curly_loop",
  "loop",
  "part_alternation_mark",
  "eight_spoked_asterisk",
  "eight_pointed_black_star",
  "sparkle",
  "bangbang",
  "interrobang",
  "question",
  "grey_question",
  "grey_exclamation",
  "exclamation",
  "wavy_dash",
  "copyright",
  "registered",
  "tm",
  "hash",
  "zero",
  "one",
  "two",
  "three",
  "four",
  "five",
  "six",
  "seven",
  "eight",
  "nine",
  "keycap_ten",
  "100",
  "capital_abcd",
  "abcd",
  "1234",
  "symbols",
  "abc",
  "a",
  "ab",
  "b",
  "cl",
  "cool",
  "free",
  "information_source",
  "id",
  "m",
  "new",
  "ng",
  "o2",
  "ok",
  "parking",
  "sos",
  "up",
  "vs",
  "koko",
  "sa",
  "u6708",
  "u6709",
  "u6307",
  "ideograph_advantage",
  "u5272",
  "u7121",
  "u7981",
  "accept",
  "u7533",
  "u5408",
  "u7a7a",
  "congratulations",
  "secret",
  "u55b6",
  "u6e80",
  "black_small_square",
  "white_small_square",
  "white_medium_square",
  "black_medium_square",
  "white_medium_small_square",
  "black_medium_small_square",
  "black_large_square",
  "white_large_square",
  "large_orange_diamond",
  "large_blue_diamond",
  "small_orange_diamond",
  "small_blue_diamond",
  "small_red_triangle",
  "small_red_triangle_down",
  "diamond_shape_with_a_dot_inside",
  "radio_button",
  "black_square_button",
  "white_square_button",
  "white_circle",
  "black_circle",
  "red_circle",
  "large_blue_circle"
];
var flagEmojis = [
  "checkered_flag",
  "cn",
  "crossed_flags",
  "de",
  "es",
  "fr",
  "gb",
  "it",
  "jp",
  "kr",
  "ru",
  "triangular_flag_on_post",
  "us"
];

var sets = ['apple', 'emojione', 'facebook', 'google', 'messenger', 'twitter']

module.exports = (options) => {
  delete require.cache[require.resolve('emoji-datasource')]
  var emojiData = require('emoji-datasource')

  var data = { compressed: true, categories: [], emojis: {}, aliases: {} },
    categoriesIndex = {}

  categories.forEach((category, i) => {
    let [name, id] = category
    data.categories[i] = { id: id, name: name, emojis: [] }
    categoriesIndex[name] = i
  })

  emojiData.sort((a, b) => {
    var aTest = a.sort_order || a.short_name,
      bTest = b.sort_order || b.short_name

    return aTest - bTest
  })

  emojiData.forEach((datum) => {
    var category = datum.category,
      keywords = [],
      categoryIndex

    if (!datum.category) {
      throw new Error('“' + datum.short_name + '” doesn’t have a category')
    }

    if (options.sets) {
      var keepEmoji = false

      options.sets.forEach((set) => {
        if (keepEmoji) return
        if (datum[`has_img_${set}`]) {
          keepEmoji = true
        }
      })

      if (!keepEmoji) {
        return
      }

      sets.forEach((set) => {
        if (options.sets.length == 1 || options.sets.indexOf(set) == -1) {
          var key = `has_img_${set}`
          delete datum[key]
        }
      })
    }

    datum.name || (datum.name = datum.short_name.replace(/\-/g, ' '))
    datum.name = inflection.titleize(datum.name || '')

    if (!datum.name) {
      throw new Error('“' + datum.short_name + '” doesn’t have a name')
    }

    datum.emoticons = datum.texts || []
    datum.text = datum.text || ''
    delete datum.texts

    if (emojiLib.lib[datum.short_name]) {
      datum.keywords = emojiLib.lib[datum.short_name].keywords
    }

    if (datum.category != 'Skin Tones') {
      categoryIndex = categoriesIndex[category]
      if (categoryIndex === 0 && smilesAndPeople.indexOf(datum.short_name) !== -1 ||
        categoryIndex === 1 && animalsAndNature.indexOf(datum.short_name) !== -1 ||
        categoryIndex === 3 && activity.indexOf(datum.short_name) !== -1 ||
        categoryIndex === 4 && travelAndPlaces.indexOf(datum.short_name) !== -1 ||
        categoryIndex === 6 && symbols.indexOf(datum.short_name) !== -1 ||
        categoryIndex === 7 && flagEmojis.indexOf(datum.short_name) !== -1) {
          data.categories[categoryIndex].emojis.push(datum.short_name)
          data.emojis[datum.short_name] = datum
      }
    }

    datum.short_names.forEach((short_name, i) => {
      if (i == 0) {
        return
      }

      data.aliases[short_name] = datum.short_name
    })

    delete datum.docomo
    delete datum.au
    delete datum.softbank
    delete datum.google
    delete datum.image
    delete datum.category
    delete datum.sort_order

    compress(datum)
  })

  var flags = data.categories[categoriesIndex['Flags']]
  flags.emojis = flags.emojis
    .filter((flag) => {
      // Until browsers support Flag UN
      if (flag == 'flag-un') return
      return true
    })
    .sort()

  fs.writeFile(options.output, JSON.stringify(data), (err) => {
    if (err) throw err
  })
}
